services:
  dev-db:
    image: postgres:15
    container_name: event-discovery-dev-db
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: postgres

networks:
  event-discovery:
